project:
  type: website
execute:
  freeze: auto
website:
  title: "Hersh Gupta"
  description: "Hersh Gupta is a data scientist working in municipal government"
  google-analytics: "G-GXXLWF1R58"
  cookie-consent: false
  favicon: static/favicon.ico
  open-graph: true
  twitter-card: true
  navbar:
    pinned: true
    left:
      - text: "About"
        href: "about.qmd"
      - text: "Talks"
        href: "talks"
    right:
      - icon: envelope
        aria-label: email
        href: "mailto:h.v.gupta@outlook.com"
      - text: "{{< fa brands bluesky >}}"
        aria-label: bluesky
        href: https://bsky.app/profile/hershgupta.com
      - icon: github
        aria-label: github
        href: https://github.com/hersh-gupta
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/hershvgupta
  search:
    location: navbar
    type: overlay
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} Hersh Gupta</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} Creative Commons CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)</span>      
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub](https://github.com/hersh-gupta/website)</span>
format:
  html:
    theme: 
      - cosmo
      - custom.scss
editor: source
pagetitle: "{{< meta title >}} | Hersh Gupta"
description-meta: "{{< meta description >}}"
author-meta: "Hersh Gupta"


